[package]
name = "devtask"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"

[[bin]]
name = "devtask"
path = "main.rs"
